# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: nikhilrrvk@gmail.com
author_name: Nikhil
contract_name: checklist
preset_name: starter
project_name: checklist

